### ISSUE TITLE
Override preferred aetheryte for node

### ISSUE THREAD

**Issue by Felys1998** [Ottermandias/GatherBuddy#39]
I noticed that the Rime Dolomite node teleports to Tertium instead of Camp Broken Glass, which is not actually closer since you have to fly north up out of the tunnel and then back around, is there any way we can override which aetheryte is preferred for a node?

**Comment by nothingfromzero** [comment]
Agreed. This particular aetheryte should be changed and/or enable changing preferred aetheryte nodes.

**Comment by Ottermandias** [comment]
Done with latest release.

**Comment by Felys1998** [comment]
Has this been pulled to the plugin repo? I have the commit that disabled flags from 3 days ago but I'm still getting TPed to tertium for Rime Dolomite.

**Comment by Ottermandias** [comment]
No idea what happened, maybe I missed committing the file. Will be done in the next release though. But I'm refactoring a lot right now.

**Comment by Felys1998** [comment]
No worries thanks for the update!
